DEFAULT_PORT = 9090
DEFAULT_CLIENT_HOST = 'localhost'
DEFAULT_SERVER_HOST = ''

MAX_CONNECTIONS = 5
MAX_SIZE_PACKAGE = 1024
ENCODING = 'utf-8'

ACTION = 'action'
TIME = 'time'

PRESENCE = 'presence'

RESPONSE = 'response'
ERROR = 'error'
ALLERT = 'allert'